import type { ZaifPair } from "./types.ts";

export const BASE_URL = "https://api.zaif.jp/api/1/";

export const ALL_ZAIF_PAIRS: ZaifPair[] = [
  "xym_jpy",
  "eth_btc",
  "cscmsxem_mosaic.cms",
  "cszaif_zaif",
  "cicc_jpy",
  "ncxc_jpy",
  "csxem_xem",
  "cicc_btc",
  "xcp_btc",
  "eth_jpy",
  "mosaic.cms_btc",
  "erc20.cms_jpy",
  "mona_jpy",
  "csbtc_btc",
  "bch_jpy",
  "fscc_btc",
  "xem_jpy",
  "ncxc_btc",
  "fscc_jpy",
  "xcp_jpy",
  "xem_btc",
  "mona_btc",
  "mosaic.cms_jpy",
  "zaif_btc",
  "cseth_eth",
  "btc_jpy",
  "xym_btc",
  "cscmseth_erc20.cms",
  "bch_btc",
  "erc20.cms_btc",
  "jpyz_jpy",
  "zaif_jpy",
];
